# Generated by Django 5.1.6 on 2025-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
